### ISSUE TITLE
unable to create folder on external storage

### ISSUE THREAD

**Issue by maxsch91** [nhasan/Airports#30]
I recently reset my phone and had to download the program again. When I start the app, it asks me to download the database. When I try to do this, I get this message "unable to create a folder on external storage." I know this is a new thing with KitKat 4.4.2 not letting apps access the SD cards. I'm rooted and I made the changes to get around that but apparently flightintel still has issues. Is there a way to download the database on internal storage? Is there a way to fix this? The message comes up even when I unmount my SD card.

**Comment by nhasan** [comment]
Sorry for the late response. Do you still have this issue?
