### ISSUE TITLE
kbtv says 24 hour control tower wrong

### ISSUE THREAD

**Issue by akalinen** [nhasan/Airports#32]
The af/d shows opening and closing times for the control tower, but the app says tower 24 hours. This is a discrepancy. Thanks!

**Comment by nhasan** [comment]
Sorry for the late response. Do you still see this data issue? Should be a problem with FAA source data. Please let me know.

**Comment by nhasan** [comment]
I have tracked down this issue. Hopefully will start on a fix soon. Stay tuned.

**Comment by nhasan** [comment]
I have fixed this issue in the latest beta version. You also need to install the current cycle data files. Please sign up for beta here: 
https://play.google.com/apps/testing/com.nadmm.airports

After sign up you will get the update for the beta version. The detailed operating hours are now available in the communications screen.
![screenshot_20160602-213638](https://cloud.githubusercontent.com/assets/564056/15766259/a446309c-290a-11e6-9cf0-53f805e88c4c.png)

**Comment by nhasan** [comment]
Closing issue since this enhancement has been released. Please verify when you can.

**Comment by akalinen** [comment]
Thanks
