### ISSUE TITLE
Bug: can't donate

### ISSUE THREAD

**Issue by libby2cm** [nhasan/Airports#33]
Google play services are out of date, so there is no way to donate and unlock app.  Please fix.. I'd like to give you money :)

**Comment by nhasan** [comment]
Thank you :)

I am working on it. The billing API v2 I am using has been retired by Google. I am working on a major update that includes new billing API. stay tuned.

**Comment by nhasan** [comment]
Billing is now fixed in v6.0 update released last weekend. Donation is working now.

**Comment by libby2cm** [comment]
Thank you!  Looks great, and already donated :-D

Keep up the good work!

**Comment by nhasan** [comment]
Thanks for your support.
