### ISSUE TITLE
Missing Documents

### ISSUE THREAD

**Issue by matthew8799** [nhasan/Airports#34]
The following documents are showing not found:
Pilot/Controller Glossary
FAA Safety Briefing May/June 2015
Instrument Procedures Handbook 2014

**Comment by rjbarber** [comment]
Same issue for me. This is one of the most useful aviation apps I have.  Thank you for all your hard work!

**Comment by nhasan** [comment]
Thanks. Do you still have this issue? It looks fine to me here.

**Comment by matthew8799** [comment]
Yes. Still showing not found on new documents.

**Comment by rjbarber** [comment]
Yes. Still showing not found if I try to select it.

 

RJ

**Comment by nhasan** [comment]
Please test now. I fixed the issue. Works fine for me now.
