### ISSUE TITLE
METAR's null after update to lollipop 

### ISSUE THREAD

**Issue by ScottHiser** [nhasan/Airports#35]
Cannot retrieve metars on Android 5.0.1. Samsung Galaxy S4.

**Comment by groobo** [comment]
Same here, no weather updates - 5.0.2, Xperia Z3

**Comment by nhasan** [comment]
The Experimental ADDS was shut down recently. I am working on an update that should fix it. Thanks for your patience.

**Comment by groobo** [comment]
Thank you. It's my favorite app for this. I will send some donation to you again to support the dev

Sent from my Sony smartphone on T-Mobile’s 4G LTE Network

---- Nadeem Hasan wrote ----

**Comment by nhasan** [comment]
I appreciate your support.

**Comment by groobo** [comment]
Do you have PayPal? 

Sent from my Sony smartphone on T-Mobile’s 4G LTE Network

---- Nadeem Hasan wrote ----

**Comment by nhasan** [comment]
Yes. nhasan@nadmm.com is my account email.

**Comment by nhasan** [comment]
groobo....thanks so much for your generous donation.

**Comment by groobo** [comment]
My pleasure. You did a great job

Sent from my Sony smartphone on T-Mobile’s 4G LTE Network

---- Nadeem Hasan wrote ----
