### ISSUE TITLE
Missing weather stations

### ISSUE THREAD

**Issue by mstrzerg** [nhasan/Airports#36]
The weather stations with 2 number and one letter identifiers (ex 2W6) do not show up in the weather station list. Their info does appear in the internal fadds database, but it isn't making it into the app.

**Comment by nhasan** [comment]
I am filtering them as of the latest app update as they are not disseminating any wx data. Why do you need to see them?

**Comment by mstrzerg** [comment]
Some of the non-ICAO airports do have weather stations and NOAA records them. See:
[2W6 Weather](https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&stationString=K2w6&hoursBeforeNow=1)

One thing to note is that despite them not being ICAO identifiers, the Aviation Weather site requires the K be added to the front of the station identifier. If they don't seem to be disseminating data, that might be a place to start.

Additionally even if they aren't sending weather at a particular time, it would be nice to see the frequency and the phone number for the AWOS.

**Comment by nhasan** [comment]
I do have them beginning with a K, like K39N. However what I see is that most of them do not publish Wx  but show up in the list causing a high signal to noise ratio. Mayble I will consider setting up a whitelist for such stations. 2W6 would be a start.

**Comment by mstrzerg** [comment]
Perhaps just filter out any that don't have a frequency or phone number in the awos1 table. This would avoid the need to create a specific whitelist.

**Comment by nhasan** [comment]
Ok I will look into this.

**Comment by mstrzerg** [comment]
Thanks for looking into it! While you are in there, it looks like military air fields aren't showing up in the weather listing either. That may or may not be working as intended to avoid some confusion, but at least when you are on that airfield's info page it could show the metar.

**Comment by nhasan** [comment]
Ok I will look into that as well. Thanks for your feedback.

**Comment by Slickh2o** [comment]
4a7 is a airport with a weather station that is reporting over the Internet in some places, it shows on some sites and not on others.  Any chance to get it to show up in my favorite preflight app(this one)

**Comment by nhasan** [comment]
Finally tracked down this issue and have it fixed in my development version. Let me know if you want to beta test it.

**Comment by nhasan** [comment]
The fix for this available in the beta version. Please sign up here:

https://play.google.com/apps/testing/com.nadmm.airports﻿

**Comment by mstrzerg** [comment]
Nadeem,

Glad to hear you were able to track this one down. I get the following when
I go to that link:
App not available

A testing version of this app hasn't been published yet or isn't available
for this account.

If you've been invited to become a tester, make sure you're signed in to
the account that was invited to the testing program. If you've been invited
to a Google Group or Google+ Community as part of the program, make sure
you've joined the Group or Community.

**Comment by nhasan** [comment]
Hmm...just tried here and it works for me. I have setup an open beta so anybody with the above link should be able to access.

**Comment by mstrzerg** [comment]
I was able to get through eventually, but now the app crashes during
startup. I sent in two crash reports one initial then a follow up one when
uninstalling and restarting didn't help. Let me know if you've got any
troubleshooting ideas.

**Comment by nhasan** [comment]
What is your device and android version? I do not see the crash reports yet, should be available soon.

**Comment by mstrzerg** [comment]
Geez, totally forgot to give the useful information... I have a Nexus 6
running Android 6.0.1

**Comment by nhasan** [comment]
Found the issue. Pushed a new build to beta channel. Please let me know if this fixes the issue.

**Comment by mstrzerg** [comment]
Everything seems to be working well! Thanks for the update.

**Comment by Slickh2o** [comment]
You got the airport i was interested in working great!  

Thanks and keep up the great work!

**Comment by nhasan** [comment]
Is the search working in the version you got?

**Comment by mstrzerg** [comment]
Nearby search works, but clicking the magnifying glass doesn't do anything.
It flashes a circle around the glass, but no dialog box comes up.

**Comment by nhasan** [comment]
I noticed that too just wanted to make sure it was not a local issue. Side
effect of fixing the crash bug. Anyway I have the fix for that in the works
and will provide update tonight.

**Comment by mstrzerg** [comment]
The new update fixed search. Everything seems to be in order now.

**Comment by nhasan** [comment]
Great. Thanks for your help. If no new issues come up I will release this
to all users over the weekend.
