### ISSUE TITLE
Blank download page

### ISSUE THREAD

**Issue by FlyingJake** [nhasan/Airports#37]
Just tried to use the program. Had a flag indicating data expired & also a message "please download the required database". Tried to download the new charts only to get a cannot start download message. Went to the download page but other than the blue basr across the top indicating the download page, is blank.

So now I can't download any data. Please help.

Ken

**Comment by edstegman** [comment]
I'm having the exact same issue. It just started today, although I haven't opened the app for a few days. I uninstalled and reinstalled and still no love

**Comment by FlyingJake** [comment]
I originally reported the issue on 12/10. It worked fine after that until just a couple of days ago. Now I'm experiencing the same issue again. I wonder if there is some glitch when the data updates? Any help would be apreciated.

**Comment by edstegman** [comment]
The downloads are working now. I would guess it was simply a matter of the new files not being ready for download.

This is a good reminder that someone is putting in their valuable time to benefit us. I'm revisiting the donation screen. I've gotten way more value from this app than I've paid for.

**Comment by FlyingJake** [comment]
You're right Ed. Nadeem has done an amazing job & I really like it. This probably happens whenever the data updates. Thanks Nadeem for your hard work.

**Comment by nhasan** [comment]
edstegman, FlyingJake:

Thanks so much for your appreciation. I have been busy lately causing data files to be delayed a few times. This should not happen anymore hopefully.

**Comment by edstegman** [comment]
Not a worry! Life happens.

**Comment by FlyingJake** [comment]
Thanks for the update Nadeem.

Ken
