### ISSUE TITLE
colors not displaying 

### ISSUE THREAD

**Issue by tdibello55** [nhasan/Airports#39]
![colors](https://cloud.githubusercontent.com/assets/19216381/15062336/0acc2524-130d-11e6-9490-d2e48529f684.png)

The circles here used to correspond to flight rules. Now they are always black.....

**Comment by nhasan** [comment]
Hmm what is the phone & Android version? Which app version? This is working fine for several of my devices on latest dev build.

**Comment by tdibello55** [comment]
Galaxy S4 version 4.4.4
It worked fine up to like a month or so ago....

**Comment by tdibello55** [comment]
Also ur app version 6.2.1

**Comment by nhasan** [comment]
I have released a version to beta channel. Can you please try and let me know if this fixes the issue?

You can sign up for beta testing here:

https://play.google.com/apps/testing/com.nadmm.airports

**Comment by nhasan** [comment]
Were you able to sign up for the beta and try the latest version?

**Comment by tdibello55** [comment]
No i never received the download

**Comment by nhasan** [comment]
Did you sign up for beta? I provided the information.

Here it is again:
https://play.google.com/apps/testing/com.nadmm.airports

**Comment by tdibello55** [comment]
OK I will try it next week I am on my way to cuba

**Comment by nhasan** [comment]
Any luck?

**Comment by tdibello55** [comment]
Hey there. I just returned home. The app is now working properly on both
Samsung devices since last week. I don't know what caused the fix as I had
not yet used the beta version. I saw a new update pushed this morning and
after that update it still works fine.

**Comment by nhasan** [comment]
If you got a new update today then you are on beta version. I have not released a stable version since April 24th. Good to hear that it works fine for you. Thanks for your help.

**Comment by tdibello55** [comment]
No problem thnks for all ur hard work!

**Comment by nhasan** [comment]
Please update your review when you can. Maybe 5 starts now?

**Comment by tdibello55** [comment]
Absolutely!

**Comment by tdibello55** [comment]
Can't get my review changed. Keeps telling me there is an error retrieving
from server.....
On Jun 7, 2016 12:46 PM, "Anthony DiBello" <anthony.dibello@gmail.com>
wrote:

Absolutely!
