### ISSUE TITLE
"Attendance" vs "Tower hours"

### ISSUE THREAD

**Issue by hmehendale** [nhasan/Airports#42]
For towered airports, having the times for ATCT operation (which are different from "Attendance") would be really awesome. This probably requires additional parsing logic for TWR hours in the dCS data.

As an example, Salinas (KSNS) attendance listed as "Attended continuously", and FlightIntel therefore shows it as "Continuous". However, there's a separate control tower hours of operation further down, which is "1400-0300 Oct-Mar, 1300-0300 Apr-Sep", which doesn't show up anywhere in the app that I could tell.

**Comment by nhasan** [comment]
Thanks for the report. ATC hours are listed under Communications screen.
